### ISSUE TITLE
Callbacks for inserted_at are missing?

### ISSUE THREAD

**Issue by schaary** [phoenixframework/phoenix_ecto#10]
I've tried phoenixframework today, which comes with phoenix_ecto. I've setup the credentials and created a migration and a model:

     $ cat priv/repo/migrations/20150412101442_create_accounts.exs
     defmodule ElixirAccounts.Repo.Migrations.CreateAccount do
       use Ecto.Migration

       def change do
         create table (:accounts) do
           add :umt_login_id, :integer
          add :firstname, :string
          add :lastname, :string
          add :birthday, :date
          add :uid, :string
          add :uid_number, :integer
          add :gid_number, :integer
          add :mail, :string
          add :password, :string
          add :umt_user_id, :string
          add :account_type, :string
          add :account_state, :string

          timestamps
        end
      end
    end

    $ cat web/models/account.ex
    defmodule ElixirAccounts.Account do
      use Ecto.Model

      schema "accounts" do
        field :uid, :string
        field :firstname, :string
        field :lastname,  :string
        field :birthday, :date
        field :mail, :string
        field :password, :string
        field :uid_number, :integer
        field :gid_number, :integer
        field :account_type, :string
        field :account_state, :string
        field :umt_login_id, :integer
        field :umt_user_id, :string
      end
    end

But I was not able to insert any data to the database by using the model:

$ iex -S mix
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.1.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> alias ElixirAccounts.Repo
nil
iex(2)> alias ElixirAccounts.Account
nil
iex(3)> account = %Account{firstname: "foo", lastname: "bar"}
%ElixirAccounts.Account{__meta__: %Ecto.Schema.Metadata{source: "accounts", state: :built}, account_state: nil, account_type: nil, birthday: nil,
 firstname: "foo", gid_number: nil, id: nil, lastname: "bar", mail: nil,
 password: nil, uid: nil, uid_number: nil, umt_login_id: nil, umt_user_id: nil}

iex(4)> Repo.insert(account)
[debug] INSERT INTO "accounts" ("account_state", "account_type", "birthday", "firstname", "gid_number", "lastname", "mail", "password", "uid", "uid_number", "umt_login_id", "umt_user_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING "id" [nil, nil, nil, "foo", nil, "bar", nil, nil, nil, nil, nil, nil] (117.6ms)
** (Postgrex.Error) ERROR (not_null_violation): null value in column "inserted_at" violates not-null constraint
               (ecto) lib/ecto/adapters/sql/worker.ex:26: Ecto.Adapters.SQL.Worker.query!/4
               (ecto) lib/ecto/adapters/sql.ex:187: Ecto.Adapters.SQL.use_worker/3
    (elixir_accounts) lib/elixir_accounts/repo.ex:2: ElixirAccounts.Repo.log/2
               (ecto) lib/ecto/adapters/sql.ex:394: Ecto.Adapters.SQL.model/5
               (ecto) lib/ecto/repo/model.ex:32: anonymous fn/8 in Ecto.Repo.Model.insert/4

Does I've oversee something?

**Comment by lancehalvorsen** [comment]
I believe you need to have `timestamps` at the bottom of the schema block in your model as well.

```elixir
defmodule ElixirAccounts.Account do
  use Ecto.Model

  schema "accounts" do
    field :uid, :string
    field :firstname, :string
    field :lastname,  :string
    field :birthday, :date
    field :mail, :string
    field :password, :string
    field :uid_number, :integer
    field :gid_number, :integer
    field :account_type, :string
    field :account_state, :string
    field :umt_login_id, :integer
    field :umt_user_id, :string

    timestamps
  end
end
```

**Comment by schaary** [comment]
You made my day! Thx

**Comment by lancehalvorsen** [comment]
And that made my day. Thank you!  :)

Also, you are going to want a changeset for your model so you can do validations, among other things. You might want to have a look at this, which I'm going to push to phoenixframework.org very soon:
https://github.com/lancehalvorsen/phoenix-guides/blob/master/H_ecto-models.md

**Comment by arthurcolle** [comment]
Another day made! Thnx (third variation on `thank you`)

**Comment by davidkuhta** [comment]
Tks (just to add a fourth)
http://www.phoenixframework.org/docs/ecto-models#section-the-model for anyone else who ends up here due to overlooking ```timestamps``` in Models, schema.
