### ISSUE TITLE
Up to date release

### ISSUE THREAD

**Issue by svarlet** [phoenixframework/phoenix_ecto#101]
Hi,

I've spent quite some time on a timeout issue which could be solved easily if a new release is published to hex with this commit: b65f3cc8e92a92553175550a08e18fbc39b2d02d.

In the meanwhile, I know I can simply point to it in my mix.exs file but I thought I would inform you that this repo has been updated a few times since the latest release.

Thanks

**Comment by svarlet** [comment]
Hmm, actually pointing to this commit in mix.exs and my issue is not solved. Basically I'm running an acceptance test which takes more than 15 seconds. I did specify a 60s timeout via the sandbox plug but the transaction keeps being checked in forcefully *and not rolled back*.

**mix.exs:**
```
defp deps do
    [
      {:phoenix_ecto, github: "phoenixframework/phoenix_ecto", ref: "b65f3cc8e92a92553175550a08e18fbc39b2d02d"},
      # and others...
    ]
end
```

**endpoint.ex**
```
defmodule AMSWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :ams

  if Application.get_env(:ams, :sql_sandbox) do
    plug Phoenix.Ecto.SQL.Sandbox,
      at: "/sandbox",
      repo: Datakeeper.Repo,
      timeout: 60_000
  end

  socket("/socket", AMSWeb.UserSocket)
  ...
end
```

Logged errors:
```
17:05:49.751 [error] Postgrex.Protocol (#PID<0.5663.0>) disconnected: ** (DBConnection.ConnectionError) owner #PID<0.5834.0> timed out because it owned the connection for longer than 15000ms
```
followed by
```
17:06:34.766 [error] GenServer #PID<0.5834.0> terminating
** (MatchError) no match of right hand side value: :not_found
    (phoenix_ecto) lib/phoenix_ecto/sql/sandbox_session.ex:27: Phoenix.Ecto.SQL.SandboxSession.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :timeout
```

Am I not passing the timeout value correctly? or is this timeout setting not the timeout I think I'm fixing?

**Comment by svarlet** [comment]
Thanks!

I just added this ownership_timeout setting to `config/text.exs`
```# Configure your database
config :datakeeper, Datakeeper.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "password",
  database: "m2020_ams_test",
  hostname: "postgres",
  pool: Ecto.Adapters.SQL.Sandbox,
  timeout: 60_000,
  ownership_timeout: 60_000,
  load_from_system_env: false
```

Now the connection is still checked in forcefully after 15 seconds... but the error says:

```
17:24:19.545 [error] Postgrex.Protocol (#PID<0.334.0>) disconnected: ** (DBConnection.ConnectionError) owner #PID<0.505.0> timed out because it owned the connection for longer than 60000ms
```

Do you still want me to try your suggestion or does this prove the presence of a bug?

**Comment by josevalim** [comment]
I think it is a bug. Do you have a sample app that reproduces the issue? Note though that the error message now at least says after 60_000ms.

**Comment by svarlet** [comment]
Hi @josevalim, while preparing a sample app I realised that things work the way they should. I think it's fine to close this issue.
