### ISSUE TITLE
phoenix_ecto 4.0 inputs_for and cast_assoc error

### ISSUE THREAD

**Issue by memolab** [phoenixframework/phoenix_ecto#107]
expected a map, got: nil
lib/phoenix_ecto/html.ex:234

**Comment by josevalim** [comment]
Can you please provide a complete bug report with a mechanism to reproduce the error? Please include versions, complete error message with complete stacktrace and let us know how you are calling the code. Otherwise there isn't much we can do to fix the error.

**Comment by memolab** [comment]
in phoenix 1.4.0-rc.3 and phoenix_ecto 4.0,  just i call new with render form
Controller:
  def new(conn, _params) do
    changeset = Accounts.change_user(%User{account: %Account{}})
    render(conn, "new.html", changeset: changeset)
  end

View:
.....
 <%= inputs_for f, :account, fn fp -> %>
    <%= text_input fp, :email %>
    <%= password_input fp, :password %>
  <% end %>
....
Complete stacktrace:
[info] GET /en/users/new
[debug] Processing with ClassroomWeb.UserController.new/2
  Parameters: %{"locale" => "en"}
  Pipelines: [:browser]
[info] Sent 500 in 24ms
[error] #PID<0.542.0> running ClassroomWeb.Endpoint (connection #PID<0.489.0>, stream id 29) terminated
Server: localhost:4001 (https)
Request: GET /en/users/new
** (exit) an exception was raised:
    ** (BadMapError) expected a map, got: nil
        (phoenix_ecto) lib/phoenix_ecto/html.ex:234: Phoenix.HTML.FormData.Ecto.Changeset.apply_action/2
        (phoenix_ecto) lib/phoenix_ecto/html.ex:46: anonymous fn/8 in Phoenix.HTML.FormData.Ecto.Changeset.to_form/4
        (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_ecto) lib/phoenix_ecto/html.ex:44: Phoenix.HTML.FormData.Ecto.Changeset.to_form/4
        (phoenix_html) lib/phoenix_html/form.ex:323: Phoenix.HTML.Form.inputs_for/4
        (classroom) lib/classroom_web/templates/user/form.html.eex:16: anonymous fn/2 in ClassroomWeb.UserView."form.html"/1
        (phoenix_html) lib/phoenix_html/form.ex:288: Phoenix.HTML.Form.form_for/4
        (classroom) lib/classroom_web/templates/user/form.html.eex:1: ClassroomWeb.UserView."form.html"/1
        (classroom) lib/classroom_web/templates/user/new.html.eex:3: ClassroomWeb.UserView."new.html"/1
        (classroom) lib/classroom_web/templates/layout/app.html.eex:39: ClassroomWeb.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:399: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:729: Phoenix.Controller.__put_render__/5
        (phoenix) lib/phoenix/controller.ex:746: Phoenix.Controller.instrument_render_and_send/4
        (classroom) lib/classroom_web/controllers/user_controller.ex:1: ClassroomWeb.UserController.action/2
        (classroom) lib/classroom_web/controllers/user_controller.ex:1: ClassroomWeb.UserController.phoenix_controller_pipeline/2
        (classroom) lib/classroom_web/endpoint.ex:1: ClassroomWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (classroom) lib/classroom_web/endpoint.ex:1: ClassroomWeb.Endpoint.plug_builder_call/2
        (classroom) lib/plug/debugger.ex:122: ClassroomWeb.Endpoint."call (overridable 3)"/2
        (classroom) lib/classroom_web/endpoint.ex:1: ClassroomWeb.Endpoint.call/2

i hope its clear, Thanks.

**Comment by josevalim** [comment]
How does your account and user schemas look like? Is there a chance your changeset/2 functions in in the `Account` schema is returning `nil`?

**Comment by memolab** [comment]
yes, 
there is nil in changeset
THANKS

**Comment by memolab** [comment]
working now, thanks.
