### ISSUE TITLE
Callback mismatch for @callback to_form/4 in Phoenix.HTML.FormData behaviour

### ISSUE THREAD

**Issue by ggerico** [phoenixframework/phoenix_ecto#112]
FYI, Dialyxir reports a  mismatch for *phoenix_ecto  @version "4.0.0"* :

> html.ex:21:callback_type_mismatch
> Callback mismatch for @callback to_form/4 in Phoenix.HTML.FormData behaviour.
> 
> Expected type:
> %Phoenix.HTML.Form{
>   :data => %{atom() | binary() => _},
>   :errors => Keyword.t(),
>   :hidden => Keyword.t(),
>   :id => binary(),
>   :impl => atom(),
>   :index => nil | non_neg_integer(),
>   :name => binary(),
>   :options => Keyword.t(),
>   :params => %{binary() => _},
>   :source => _
> }
> 
> Actual type:
> [any()]

**Comment by josevalim** [comment]
Thanks, fixed in Phoenix.HTML.
