### ISSUE TITLE
Project license unclear

### ISSUE THREAD

**Issue by dideler** [phoenixframework/phoenix_ecto#113]
[The package metadata, used by Hex, says Apache 2.0.](https://github.com/phoenixframework/phoenix_ecto/blob/c6b448f43c4591e6fd37f02ea0cb0968bb6dc2ab/mix.exs#L39)

[The README and LICENSE file says MIT.](https://github.com/phoenixframework/phoenix_ecto/blob/master/LICENSE)

Is there a discrepancy or is the project meant to be dual-licensed?

**Comment by josevalim** [comment]
Good catch. Probably a copy and paste error on the mix.exs. Thanks!
