### ISSUE TITLE
Advanced select

### ISSUE THREAD

**Issue by kurmetaubanov** [phoenixframework/phoenix_ecto#114]
Hi Jose Valim, i appreciate your work very much.

Please, can i get help or assistance in solving this problem in ecto.

I often use SQL with this type of selects:

SELECT a.data FROM table AS a
WHERE a.id = (SELECT b.id FROM another_table AS b WHERE b.data=something ORDER_BY b.order DESC LIMIT 1)

etc.

I know now this can by done using fragments. But in fragment I need to use another_table name as it is in SQL, but not as it is in Ecto.Schema defmodule.

Is there a way to do that type of advanced selects in Ecto or to use Ecto.Schema defmodule name in fragments?

Thanks in advance,
Sincerely and with respect to you
Kurmet

**Comment by josevalim** [comment]
Hi @kurmetaubanov, glad to hear you are enjoying Elixir.  Unfortunately I  am quite time constrained, but you can use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help/feedback, where a wider community will be able to help you. Thanks!
