### ISSUE TITLE
Do not require `as:` option

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix_ecto#117]
Recent versions of phoenix_html no longer require an `as:` option for `form_for`, but phoenix_ecto does still enforce the usage of one, when schemaless changesets are used.

**Comment by josevalim** [comment]
A pull request is welcome, thanks!

**Comment by chrismccord** [comment]
@LostKobrakai if you'd like to submit a PR, please do. Thanks!
