### ISSUE TITLE
inputs_for :append/:prepend options don't add inputs if there is an error in the changset

### ISSUE THREAD

**Issue by thojanssens** [phoenixframework/phoenix_ecto#118]
According to this test:
https://github.com/phoenixframework/phoenix_ecto/blob/master/test/phoenix_ecto/inputs_for_test.exs#L445

It is assumed we don't want to append/prepend blank inputs when there is an error in the changeset. But why?

If a form is submitted (for a new record) with errors (for example for some other field in the form), the extra inputs won't show, and it is then impossible to submit data for the association (I'm thinking here about an embed_many association). So we end up with a label with no inputs below it (weird), and if there is a not null constraint in DB, it is not possible to submit a correct form without these inputs.

**Comment by josevalim** [comment]
It is done like that because the idea is to show those inputs only on the initial render. It is meant to be something like: "if you want to add a new embed, start feeling this one here". Otherwise, whenever there is an error, we will add a bunch of more fields, and so on and so on.

 But this is just tiny convenience. You can render any new inputs yourself, for example by using JS.

**Comment by thojanssens** [comment]
I thought it would somehow be possible to make sure only one extra set of blank inputs are rendered in case of (recurrent) errors (instead of adding them up - which is the problem you mentioned). It's a pity that I will have to use JS just because of that, because in my case it's just an admin interface, I need the most basic thing that works. I do not see many use cases for the current behavior.

**Comment by thojanssens** [comment]
Sorry, if an error occurs on a field, the extra prepended/appended fields do not disappear. I had a problem with my changeset (didn't use cast_embed properly), which had the side-effect that it made the fields disappear.

Everything is working fine and it is then a nice convenience.
