### ISSUE TITLE
(chore): upgrade to latest ecto version

### ISSUE THREAD

**Issue by daniellizik** [phoenixframework/phoenix_ecto#123]
Currently it seems like [phoenix_eco](https://github.com/phoenixframework/phoenix_ecto/blob/master/mix.exs#L53) is at ecto 3.0. In ecto 3.2.1 they introduced [`Ecto.Changeset.validate_exclusion`](https://hexdocs.pm/ecto/3.2.1/Ecto.Changeset.html#validate_exclusion/4) which I'd like to utilize. Is it possible to update? Thanks for your time.

**Comment by josevalim** [comment]
You can update it in your app. “mix deps.update ecto”. This project with any version after 3.0.

**Comment by daniellizik** [comment]
oh ok thanks
