### ISSUE TITLE
Error on inputs_for when using with MFA option on cast_assoc

### ISSUE THREAD

**Issue by francocatena** [phoenixframework/phoenix_ecto#125]
Hi,

I'm using the `with` MFA option on `cast_assoc` as suggested in: https://hexdocs.pm/ecto/Ecto.Changeset.html#cast_assoc/3-options. When I try to use `inputs_for` it raises an exception:

> no function clause matching in Phoenix.HTML.FormData.Ecto.Changeset.to_changeset/4

The code is similar to the following:

```elixir
defmodule Movie do
  schema "movies" do
    field :name, :string

    many_to_many :videos, Video, join_through: "movies_videos"

    timestamps()
  end

  def changeset(prefix, %Movie{} = movie, attrs) do
    movie
    |> cast(attrs, [:name])
    |> cast_assoc(:videos, required: true, with: {Video, :changeset, [prefix]})
    |> validate_required([:name])
  end
end

defmodule Video do
  schema "videos" do
    field :name, :string

    timestamps()
  end

  def changeset(changeset, params, prefix) do
    put_prefix(changeset, prefix)
  end
end
```

And the template:

```html+eex
<%= form_for @changeset, @action, fn f -> %>
  <%= text_input f, :name %>

  <%= inputs_for f, :videos, fn v -> %>
    <%= text_input v, :name %>
  <% end %>
<% end %>
```

The `Video.changeset/3` function always returns a changeset. I am doing something wrong?

If this is indeed a bug I'll be happy to help, just point me on the right direction and I'll be back with a pull request.

**Comment by josevalim** [comment]
Hi @francocatena ! THe fix is to add a new clause here that handles the tuple: https://github.com/phoenixframework/phoenix_ecto/blob/c49af30c958b849466620e7f91285e02d8ea050b/lib/phoenix_ecto/html.ex#L236

A PR with a fix is welcome but if a fix is too complicated, simply a PR that adds a failing test would already help us a lot. Thank you!

**Comment by francocatena** [comment]
Hi @josevalim, thank you very much for your feedback, it made the change a lot easier. I've created a new PR, any comment on that is welcome!
