### ISSUE TITLE
Navigation bar link showing un-decoded HTML entities title.

### ISSUE THREAD

**Issue by kianmeng** [phoenixframework/phoenix_ecto#135]
![Screenshot-20210130164014-436x76](https://user-images.githubusercontent.com/134518/106351974-8e24ad80-631a-11eb-9541-0eb8586ca9dc.png)

Dep of `ex_doc` in `mix.lock` needs to be upgrade to 0.23

**Comment by josevalim** [comment]
Done, thanks!
