### ISSUE TITLE
String keys in form input helpers

### ISSUE THREAD

**Issue by miguel-s** [phoenixframework/phoenix_ecto#138]
Hi!
While implementing the form components in Surface (PR https://github.com/surface-ui/surface/pull/319) I've run into an error with phoenix_ecto when using changesets and string keys.

Controller
```Elixir
def index(conn, _params) do
  changeset = Accounts.change_user(%User{})
  render(conn, "index.html", changeset: changeset)
end
```

Template
```Elixir
<%= form_for @changeset, "#", fn f -> %>
  <label>
    Name: <%= text_input f, "name" %>
  </label>
  <%= submit "Submit" %>
<% end %>
```

Error

> ** (ArgumentError) argument error
> :erlang.atom_to_binary("name", :utf8)
> (phoenix_ecto 4.2.1) lib/phoenix_ecto/html.ex:111: Phoenix.HTML.FormData.Ecto.Changeset.input_value/4
> (phoenix_html 2.14.2) lib/phoenix_html/form.ex:482: Phoenix.HTML.Form.input_value/2
> (phoenix_html 2.14.2) lib/phoenix_html/form.ex:825: Phoenix.HTML.Form.generic_input/4

It looks like support for string keys was added to phoenix_html a while ago with this PR https://github.com/phoenixframework/phoenix_html/pull/198. But from what I can tell so far phoenix_ecto has not added support for string keys, based on this piece of code https://github.com/phoenixframework/phoenix_ecto/blob/54623ef9ead9053b50f8079618f1973e73dfc2f4/lib/phoenix_ecto/html.ex#L105

Should we add support for string keys to phoenix_ecto or at least show a warning?

**Comment by josevalim** [comment]
We have two options:

1. Raise a better error message since we require atom keys because the values in the changeset are atom keys
2. Return nil

If we force you to use atom keys, will that work for you?

**Comment by miguel-s** [comment]
Yes, I believe showing a nice error message would be enough 👍

**Comment by josevalim** [comment]
Sweet, a PR is welcome!
