### ISSUE TITLE
Phoenix.Ecto.CheckRepoStatus.init/1 is undefined 

### ISSUE THREAD

**Issue by kypse** [phoenixframework/phoenix_ecto#142]
Hi There,

When creating a new umbrella project and simple run using mix phx.server it is showing the  following error:

UndefinedFunctionError at GET /
function Phoenix.Ecto.CheckRepoStatus.init/1 is undefined (module Phoenix.Ecto.CheckRepoStatus is not available)

This issue doesn't happen when create a new project without a umbrella command.

**Comment by josevalim** [comment]
Hi @kypse, can you please provide more information? How are you creating the umbrella? Which Elixir and Phoenix versions? Can you provide a minimal app that reproduces it?

What is most likely happening is that the project is not depending on phoenix_ecto directly.

**Comment by kypse** [comment]
Hi @josevalim ,

Sorry for delay in my response. During the day employee and at night a dreamer. ;)

elixir -v
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]
Elixir 1.12.2 (compiled with Erlang/OTP 24)

mix phx.new --version
Phoenix v1.5.9
Mix 1.12.2 (compiled with Erlang/OTP 24)

Please attached the output for a testing project.
[create_project.txt](https://github.com/phoenixframework/phoenix_ecto/files/7010258/create_project.txt)
<img width="1464" alt="Screen Shot 2021-08-18 at 18 17 26" src="https://user-images.githubusercontent.com/1817310/129974111-243520f9-2c61-42fb-8173-088c4a3217fd.png">
[project_start.txt](https://github.com/phoenixframework/phoenix_ecto/files/7010261/project_start.txt)


Thanks for your reply.

**Comment by josevalim** [comment]
I think for some reason your app is getting a very old version of phoenix_ecto. Can you please send your mix.lock too?

**Comment by josevalim** [comment]
Do this. Find the mix.exs under _web and replace this:

    {:phoenix_ecto, "~> 4.0"},

By this:

    {:phoenix_ecto, "~> 4.4"},

I will push a fix to the generator.

**Comment by josevalim** [comment]
And thanks for the report!

**Comment by kypse** [comment]
Great!
Thank you! Obrigado!
