### ISSUE TITLE
Distinguish queries made by phoenix_ecto

### ISSUE THREAD

**Issue by fuelen** [phoenixframework/phoenix_ecto#152]
I work on an alternative logger for Ecto which uses telemetry https://github.com/fuelen/ecto_dev_logger
And the issue I have currently, is that I cannot distinguish queries made by `Phoenix.Ecto.CheckRepoStatus` plug and by my application, so on every HTTP request I see the following logs:
```
[debug] QUERY OK db=0.3ms decode=1.5ms
CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" bigint, "inserted_at" timestamp(0), PRIMARY KEY ("version"))
[debug] QUERY OK db=0.4ms
begin
[debug] QUERY OK db=0.3ms
LOCK TABLE "schema_migrations" IN SHARE UPDATE EXCLUSIVE MODE
[debug] QUERY OK source="schema_migrations" db=0.4ms
SELECT s0."version"::bigint FROM "schema_migrations" AS s0
[debug] QUERY OK db=0.3ms
commit
```
It would be great if there is something in telemetry metadata that could help me to hide such logs.

P.S: Maybe, that's an issue in ecto/ecto_sql?

**Comment by josevalim** [comment]
I think you can pass `log: false` to the check status plug? If so, can you please:

1. Document the log: false option
2. Change Phoenix generators to pass log: false by default?

**Comment by fuelen** [comment]
Sorry, I didn't get the idea with `log: false`.
`log: false` is a requirement to use my custom logger in order not to duplicate logs.
According to this code
https://github.com/elixir-ecto/ecto_sql/blob/c73ba2b1edf9d049804c2103d7dd4c9d28e6c59d/lib/ecto/adapters/sql.ex#L1107-L1120
telemetry event is published even if `log: false`

**Comment by josevalim** [comment]
Oh, I understand now. IIRC, we started adding some option for migration queries, something like `:migration_source`? Please inspect all telemetry metadata and see if there is something you can use.

If not, I think you can pass `telemetry_options: %{dev_logger: false}` to the Plug too.

Finally, you should consider sending the improvements in `ecto_dev_logger` upstream. I know @v0idpwn was excited about the package. At least the coloring changes should be a no-brainer. We would love to have coloring for stacktrace, for the db timing, etc. :)

**Comment by fuelen** [comment]
>  Please inspect all telemetry metadata and see if there is something you can use.

Nope, here is one small example of metadata
```elixir
%{
  options: [],
  params: [],
  query: "commit",
  repo: MyApp.Repo,
  result: {:ok,
   %Postgrex.Result{
     columns: nil,
     command: :commit,
     connection_id: 68112,
     messages: [],
     num_rows: nil,
     rows: nil
   }},
  source: nil,
  stacktrace: nil,
  type: :ecto_sql_query
}
```

Passing additional options to the Plug also does not help.


> We would love to have coloring for stacktrace, for the db timing, etc. :)

Good to know, I'll open a discussion later :)

**Comment by josevalim** [comment]
> Passing additional options to the Plug also does not help.

We should support that, so PRs here are welcome too!

**Comment by greg-rychlewski** [comment]
@fuelen you should be able to see `schema_migration: true` in the telemetry options using `ecto_sql` master

**Comment by fuelen** [comment]
@greg-rychlewski I tried it and `schema_migration: true` is present only for these log lines:
```
CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" bigint, "inserted_at" timestamp(0), PRIMARY KEY ("version"))
```
```
SELECT s0."version"::bigint FROM "schema_migrations" AS s0
```
so, the option is absent for `begin`, `commit` and `LOCK TABLE ...`

**Comment by josevalim** [comment]
Ah, yes. Those are in different files and we need to set them too.

**Comment by greg-rychlewski** [comment]
@fuelen Thanks for catching that. Now it should be fixed in ecto_sql master.
