### ISSUE TITLE
Release with Ecto 0.13 support

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_ecto#16]

**Comment by josevalim** [comment]
This works fine with 0.13. The plan is to release a new one with features coming in v0.14.

**Comment by josevalim** [comment]
Once v0.14 hits, we will need to update Phoenix to no longer generate Ecto.Date, Ecto.DateTime and Ecto.Time.

**Comment by chrismccord** [comment]
We still need to bump the ecto dep don't we? It will only pull down 0.12 right?

**Comment by josevalim** [comment]
No, it is: `{:ecto, "~> 0.12"}`

**Comment by josevalim** [comment]
Note to self: we will also need to do `if changeset.action` instead of `if changeset.errors != []`.
