### ISSUE TITLE
`to_form` does not copy the `:action` field

### ISSUE THREAD

**Issue by Gladear** [phoenixframework/phoenix_ecto#163]
## Expected

I expected the `:action` field of the changeset to be copied to the form when using `to_form`

```ex
iex> Phoenix.Component.to_form(%Ecto.Changeset{action: :validate}, as: :foo)
%Phoenix.HTML.Form{action: :validate, ...}
```

## Got

`:action` is not set

```ex
iex> Phoenix.Component.to_form(%Ecto.Changeset{action: :validate}, as: :foo)
%Phoenix.HTML.Form{action: nil, ...}
```

**Comment by Gladear** [comment]
Digging a little more, I found [that comment](https://github.com/phoenixframework/phoenix_html/blob/77db8d5e4e4d56dce2b8d83296263afc8dcbbb65/lib/phoenix_html/form.ex#L2) indicating `form.action` is deprecated... I wonder why ? I guess it was too specific for changesets ? Maybe it should start being undocumented ?

**Comment by josevalim** [comment]
The form.action was the form URL (as in the HTML element) and we deprecated exactly because it was confusing. So it never behaved the way you expected. You can still get the action under form.source.action.
