### ISSUE TITLE
Duplicate beam files (Poison encoders)

### ISSUE THREAD

**Issue by olgeni** [phoenixframework/phoenix_ecto#18]
Hi,

There is some overlap between ecto and phoenix_ecto for the Poison encoders.

phoenix_ecto builds these beam files:

    Elixir.Poison.Encoder.Decimal.beam
    Elixir.Poison.Encoder.Ecto.Changeset.beam
    Elixir.Poison.Encoder.Ecto.Date.beam
    Elixir.Poison.Encoder.Ecto.DateTime.beam
    Elixir.Poison.Encoder.Ecto.Time.beam

ecto has these:

    Elixir.Poison.Encoder.Decimal.beam
    Elixir.Poison.Encoder.Ecto.Date.beam
    Elixir.Poison.Encoder.Ecto.DateTime.beam
    Elixir.Poison.Encoder.Ecto.Time.beam

Looking at the source they are mostly the same, but phoenix_ecto has encoding for Changeset too. Right now we have duplicate beam files in the code path; could they all be merged into ecto including Changeset, and removed from phoenix_ecto?

**Comment by josevalim** [comment]
They have already been removed from phoenix ecto, except the changeset one which is phoenix specific.

**Comment by olgeni** [comment]
Great - I saw it before the upgrade. Thanks! :+1:
