### ISSUE TITLE
Request to cut a new release tag

### ISSUE THREAD

**Issue by echotrain** [phoenixframework/phoenix_ecto#182]
Would it be possible to cut a release with the latest changes to `main`? 

The last release (`4.6.2`) was in June, and there have been a few updates since then. One of which specifically addresses an issue I'm currently running into (albeit a very small nit-picky issue 😅). 

I would love to update the dependency rather than pointing to a particular commit SHA, or forking the repo, etc. 

Thank you for considering!

**Comment by josevalim** [comment]
Done.
