### ISSUE TITLE
migration with SQL - syntax error reporting

### ISSUE THREAD

**Issue by InoMurko** [phoenixframework/phoenix_ecto#22]
Hi,
for example:
defmodule HelloPhoenix.Repo.Migrations.UpdateTimestampFields do
  use Ecto.Migration
  def up do
    "ALTER TALBE posts ALTER COLUMN created_at TYPE date"
  end
end
--------------------
See "TALBE" ...
--------------------
Running this produces:
mix ecto.migrate Repo

12:44:32.151 [info]  == Running HelloPhoenix.Repo.Migrations.UpdateTimestampFields.up/0 forward
12:44:32.155 [info]  == Migrated in 0.0s

--------------------
Expected to see something like:
ERROR:  syntax error at or near "TALBE"

**Comment by josevalim** [comment]
That's a very old syntax no longer supported by Ecto migrations. Please check Ecto.Migration for reference on the matter.
