### ISSUE TITLE
inputs_for should iterate over the related models contents if no changes were given

### ISSUE THREAD

**Issue by sumerman** [phoenixframework/phoenix_ecto#24]

**Comment by josevalim** [comment]
I don't follow this one.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by sumerman** [comment]
@josevalim now if I want to show currently present items I have manually convert them to params and call cast. E.g.:
```elixir
nested = build_nested_params(model.nested)
changeset = Model.changeset(changeset, %{"nested" => nested})
```
If I don't do this I get an empty form.

Which is quite as written in the source [here](https://github.com/phoenixframework/phoenix_ecto/blob/master/lib/phoenix_ecto/html.ex#L53) and [here](https://github.com/phoenixframework/phoenix_ecto/blob/master/lib/phoenix_ecto/html.ex#L33)

**Comment by josevalim** [comment]
Can you tell me if it would work if you build it as:

    changeset = Model.changeset(changeset, :empty)

I am almost sure it is required to build a changeset. The `:empty` parameters does it for you.

**Comment by sumerman** [comment]
It does if I put a model instead of changeset as a first parameter. But in my particular case, a controller's action already have params, so it becomes `Model.changeset(Model.changeset(model), params)` which is not very intuitive and should be documented at least.

**Comment by josevalim** [comment]
@sumerman I see and I agree. I will try to find a solution.

**Comment by sumerman** [comment]
@josevalim thanks for this and for all your work.

**Comment by josevalim** [comment]
Ok, this is more complicated than expected because, for embeds, the data is always there... which means defaults would never be triggered.

When are you first generating the changeset? Are you generating it with the `:empty` parameter?

**Comment by sumerman** [comment]
First time it's generated by another controller action, then it's shown as a form to a user who modifies it then it shown as immutable part of the form which becomes a param-only initialization. Also there is a problem with `Model.changeset(Model.changeset(model), params)` but I will open a separate issue on `elixir-lang/ecto` for it.

**Comment by josevalim** [comment]
Fixed in master. We now always take the value in the model into account.
