### ISSUE TITLE
Error when updated a model with derived key

### ISSUE THREAD

**Issue by phongmh307** [phoenixframework/phoenix_ecto#29]
For some reason, I have to add option: `@derive {Phoenix.Param, key: :_id}` to my model.
This error happened after that

```
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Mongo.Ecto.update/7
        (mongodb_ecto) lib/mongo_ecto.ex:483: Mongo.Ecto.update(Snappy.Repo, %{context: nil, model: Snappy.Tracking, source: {nil, "trackings"}, state: :loaded}, [current_status: "picked_up", external_carrier: "VTP", external_tracking: "SNPE37043100000186", updated_at: {{2015, 12, 8}, {21, 3, 49, 0}}], [_id: "E37043100000186"], nil, [], [])
        (ecto) lib/ecto/repo/model.ex:253: Ecto.Repo.Model.apply/4
        (ecto) lib/ecto/repo/model.ex:152: anonymous fn/10 in Ecto.Repo.Model.do_update/4
        (ecto) lib/ecto/repo/model.ex:25: Ecto.Repo.Model.update!/4
```

**Comment by chrismccord** [comment]
Where is the `_id` field coming from? What ecto adapter are you using?

**Comment by phongmh307** [comment]
Here is from my mix.lock
```
  "mongodb_ecto": {:hex, :mongodb_ecto, "0.1.2"},
  "ecto": {:hex, :ecto, "1.0.7"},
  "mongodb": {:hex, :mongodb, "0.1.0"},
```

This is my update call
```
		Ecto.Changeset.change(tracking)
			|> Ecto.Changeset.put_change(:external_carrier, "VTP")
			|> Ecto.Changeset.put_change(:external_tracking, "SNP" <> order_id)
			|> Ecto.Changeset.put_change(:current_status, "picked_up")
			|> Repo.update!
```

**Comment by phongmh307** [comment]
and the _id type is `string`, not `binary_id`

**Comment by ericmj** [comment]
Can you show your schema?

**Comment by michalmuskala** [comment]
Especially the `@primary_key` configuration.

**Comment by phongmh307** [comment]
here it is. Thank you guys so much
```
defmodule App.Tracking do
  use App.Web, :model

  @primary_key {:_id, :string, []}
  @derive {Phoenix.Param, key: :_id}
  @derive {Poison.Encoder, only: [
    :_id, :is_external, :external_carrier, :external_tracking, :business_id,
    :current_status, :balance_adjustment, :inserted_at, :updated_at, :modifications
  ]}
  schema "trackings" do
    field :is_external,           :boolean, default: false
    field :external_carrier,      :string
    field :external_tracking,     :string
    field :current_status,        :string
    field :balance_adjustment,    :integer
    field :business_id,           :binary_id
    
    embeds_many :modifications, App.PackageModification
    
    timestamps
  end

  @required_fields ~w(_id is_external current_status balance_adjustment)
  @optional_fields ~w(external_carrier external_tracking business_id modifications business_id)

  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end
```

**Comment by ericmj** [comment]
Your primary key should be `id`.

**Comment by michalmuskala** [comment]
It can be `_id`. We should be able to handle any name for the primary key, it should be converted to `_id` for mongo, as that's the only thing mongo will accept. The part that is causing issues is that the `@primary_key` is not `autogenerate: true`. Without this option we can't really do the primary key name conversion, but with `_id` for a name it should work nicely.
We're missing a clause in the adapter.

**Comment by ericmj** [comment]
> It can be _id.

Yes, but `Phoenix.Param` defaults to `id`. Hence the need for `@derive {Phoenix.Param, key: :_id}` which I believe was the original issue.

**Comment by phongmh307** [comment]
I need to customize `_id` to fit with our old Rails code. If I just set it to `@primary_key {:id, :string, []}`
it will still generate a `_id` automatically and also another `id` with the param that I passed in

**Comment by michalmuskala** [comment]
Why `:string` for the primary key?
If you set `@primary_key {:id, :binary_id, autogenerate: true}` we should translate `:id` on application level to `_id` on database level.

**Comment by phongmh307** [comment]
Because our old Rails code using a customized string for `_id`. We are building another application that using the same db.

**Comment by josevalim** [comment]
Please open up an issue on Mongo.Ecto. :)

**Comment by phongmh307** [comment]
I really apologize for the inconvenience. I was searching both repo and posted here by mistake.

Reposted at: https://github.com/michalmuskala/mongodb_ecto/issues/53

**Comment by josevalim** [comment]
It is not an inconvenience at all. Pretty much the same people would end-up reading it anyway :P
