### ISSUE TITLE
Phoenix Ecto Integration Should Generate Complete Migration File

### ISSUE THREAD

**Issue by conradwt** [phoenixframework/phoenix_ecto#32]
It appears that the migration process generates an empty migration file instead of a fully formed executable migration file.  Thus, here are my findings using `phoenix_ecto 2.0` and `phoenix 1.1.0` as I work through the `Programming Phoenix` ebook.

user.ex:

```
defmodule Rumbl.User do 
  use Rumbl.Web, :model
  
  schema "users" do
    field :name, :string
    field :username, :string
    field :password, :string, virtual: true 
    field :password_hash, :string
    
    timestamps
  end 
end
```

```
$ mix ecto.gen.migration create_user
```

priv/repo/migrations/20160103224338_create_user.exs:

`expected`

```elixir
defmodule Rumbl.Repo.Migrations.CreateUser do 
  use Ecto.Migration

  def change do
    create table(:users) do
      add :name, :string
      add :username, :string, null: false 
      add :password_hash, :string
      
      timestamps
    end

    create unique_index(:users, [:username]) 
  end
end
```

`actual`

```elixir
defmodule Rumbl.Repo.Migrations.CreateUser do
  use Ecto.Migration

  def change do
  end
end
```

Lastly, there might be a bit of duplication with `field field_name` statements within the model and the `add field_name` statements within the migration but I prefer to just see this information within the model.

**Comment by chrismccord** [comment]
Echo's migration generator only generates a blank migration, so the code output is expected.

Perhaps you meant to write: `mix phoenix.gen.html User users name:string ...` ?

**Comment by conradwt** [comment]
@chrismccord I'm following the example on page 54 of the PDF.  Thus, should I be using the following instead to generate both the model and the migration file: 

```
mix phoenix.gen.html User users name:string ...
```

**Comment by chrismccord** [comment]
The text in the book is not as clear as it could be, but it is instructing you to manually key in those fields after you run `mix ecto.gen.migration`. Later, when the book introduces generators, you see how it is done for you.

**Comment by ChrisZou** [comment]
I also found it unclear. Hope this part would get updated in the next version.

**Comment by Lubmes** [comment]
Wouldn't it be a great addition though? When you've defined your model, to be able to generate a blueprinted migration. Maybe even after changes, to be able to generate an add / remove column migration automatically. 

Downside I guess is maybe that this makes programmers lazy and easily dismiss the advantages of indexing etc.
