### ISSUE TITLE
Ecto callbacks, how to write them

### ISSUE THREAD

**Issue by VladShcherbin** [phoenixframework/phoenix_ecto#36]
Since Ecto callbacks are deprecated now, how do we handle after/before actions now? Before actions can be done using changesets, but what about after callbacks.

I need to broadcast an event after data is inserted. Any even simple example how to do it now?

**Comment by josevalim** [comment]
Broadcast in your controller, that's exactly the kind of actions we ask to not do in callbacks. Specially because callbacks run even if the transaction is rolledback. Also, please use the mailing list as previously asked. Thank you.
