### ISSUE TITLE
Build ecto master on CI

### ISSUE THREAD

**Issue by wojtekmach** [phoenixframework/phoenix_ecto#39]
I just noticed that `phoenix_ecto` build is broken when integrated with the latest `ecto` master. Do you think this a problem likely to occur frequently (and thus worth adding some alerts), or it doesn't matter much?

I have heard about other OSS projects that are catching integration issues early on by using e.g. CI build matrices and pointing upstream deps to master branches. I took a stab at it and it was relatively easy to do, albeit mix.exs got more complicated. See: https://travis-ci.org/wojtekmach/phoenix_ecto/builds/116899223, https://github.com/wojtekmach/phoenix_ecto/commit/ffb28524a36cfa8f95423a9e4b968a8a19e8f025

Please let me know if you'd be interested in this change, and I'm happy to open up a PR. Thanks!

**Comment by josevalim** [comment]
I am not a huge fan because I don't think phoenix_ecto should break when a dependency that is in development breaks. It is not supposed to happen frequently anyway!

**Comment by josevalim** [comment]
(Btw, I see it is an allowed failure but I am still not sure it is worth it).

**Comment by josevalim** [comment]
Thank you!
