### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_ecto#4]
@jeregrine @drewolson @paulcsmith, to release I am waiting on your feedback here:

https://github.com/phoenixframework/phoenix_ecto/blob/master/lib/phoenix_ecto/json.ex

And the tests:

https://github.com/phoenixframework/phoenix_ecto/blob/master/test/phoenix_ecto/json_test.exs

Date, Time, DateTime and Decimal are all represented as strings. We also implemented JSON rendering for changesets and all we do is to render the errors as a JSON object.

If you are OK with those, I am releasing v0.2.0 and updating Phoenix master to depend on it.

Thank you! <3

**Comment by josevalim** [comment]
Also /cc @chrismccord.

**Comment by jeregrine** [comment]
:+1: I probably wouldn't use the changeset but I think its good to have a sensible default. And if we are including this with phoenix wouldn't poison always be loaded?

**Comment by chrismccord** [comment]
:shipit:

**Comment by paulcsmith** [comment]
Looks great! Just one thought.

I think I would want the changeset with errors to be encoded with an `errors` key. Otherwise how would I check if there were errors? I think it should be encoded with an `errors` key for the same reason that the errors in the changeset are in an errors key.

**Comment by paulcsmith** [comment]
I would also consider extracting a function to make it easy to tell what Map.reduce is doing. Maybe something like: https://gist.github.com/paulcsmith/e19d077a8422cd2f86b4 ?

**Comment by drewolson** [comment]
Looks good to me.

**Comment by josevalim** [comment]
@jeregrine the idea is that Phoenix.HTML will be usable outside of Phoenix too. I think Hex plans to use it. So it will depend on phoenix_html and poison but as optional dependencies.

@paulcsmith I thought about leaving the errors key to the user. So they just need to do `%{errors: changeset}` and that is it. A pull request to clean up the code is welcome. :)

**Comment by josevalim** [comment]
Thank you everyone, new version released!

**Comment by paulcsmith** [comment]
@paulcsmith: That makes sense. More flexible.
