### ISSUE TITLE
Optimistic Lock - StaleModelError for both Repo.update and Repo.update!

### ISSUE THREAD

**Issue by yial2** [phoenixframework/phoenix_ecto#42]
Hi,

I am **NOT** sure if this is even an issue or this is is by design, so please forgiving my ignorance. Elixir/Phoenix newbie here.

I understand that Repo.update! will raise StaleModelError if DB conflicts are encountered, but from my understanding, Repo.update should return an error **tuple** (e.g. {:error, changeset}). What I am seeing is that Repo.update is also raising the error, so I have to do **try....rescue** for now.

I am using phoenix_ecto 2.0, which I think it is Ecto 1.1.5 under the hood. I believe Ecto 2.0 beta is showing the same behavior, which leads me to think this is how it is designed to begin with. Again, if this is the case, please pardon me for filing this as an issue.

Many Thanks,
Allen

**Comment by josevalim** [comment]
@yial2 it is by design because it is impossible for us to know if the stale model was because of the lock or because it was removed or even something else. Enjoy!
