### ISSUE TITLE
mix ecto.migrate on ecto 2.0.0-rc.0

### ISSUE THREAD

**Issue by flomop** [phoenixframework/phoenix_ecto#45]
I tried to make **mix ecto.migrate** in my Phoenix application and surprisingly found the following error:

    warning: could not find repositories for application :adah.

    You can avoid this warning by passing the -r flag or by setting the
    repositories managed by this application in your config files:

      config :adah, ecto_repos: [...]

    The configuration may be an empty list if it does not define any repo.

    ** (Protocol.UndefinedError) protocol Enumerable not implemented for :ok
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1486: Enum.reduce/3
    (elixir) lib/enum.ex:609: Enum.each/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2

My deps are:

    phoenix_ecto: 3.0.0-rc.0
    ecto: 2.0.0-rc.0
    ...

My config files have the following lines:

    dev.ex:

    # Configure your database
     config :adah, Adah.Repo,
       adapter: Ecto.Adapters.Postgres,
       username: "postgres",
       password: "postgres",
       database: "adah_dev",
       hostname: "localhost",
       pool_size: 10

    test.ex: 

    # Configure your database
     config :adah, Adah.Repo,
     adapter: Ecto.Adapters.Postgres,
     username: System.get_env("POSTGRES_USER") || "postgres",
     password: System.get_env("POSTGRES_PASSWORD") || "postgres",
     database: System.get_env("POSTGRES_DB") || "adah_test",
     hostname: System.get_env("POSTGRES_HOST") || "localhost",
     pool: Ecto.Adapters.SQL.Sandbox

And I have no such errors while running tests or serving pages in dev environment, only when I run **mix ecto.migrate**.

**When I use {:ecto, "== 2.0.0-beta.2", :phoenix_ecto, "== 3.0.0-beta.2"} everything works as excepted!**

**Comment by josevalim** [comment]
This is not meant to be a warning but an error. Please do what is suggested
in themes sage and you should be good. I will fix the message soon. Thank
you! :)

On Sunday, April 17, 2016, flomop <notifications@github.com> wrote:

> I tried to make *mix ecto.migrate* in my Phoenix application and
> surprisingly found the following error:
>
> warning: could not find repositories for application :adah.
>
> You can avoid this warning by passing the -r flag or by setting the
> repositories managed by this application in your config files:
>
>   config :adah, ecto_repos: [...]
>
> The configuration may be an empty list if it does not define any repo.
>
> ** (Protocol.UndefinedError) protocol Enumerable not implemented for :ok
> (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
> (elixir) lib/enum.ex:116: Enumerable.reduce/3
> (elixir) lib/enum.ex:1486: Enum.reduce/3
> (elixir) lib/enum.ex:609: Enum.each/2
> (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
>
> My deps are:
>
> phoenix_ecto: 3.0.0-rc.0
> ecto: 2.0.0-rc.0
> ...
>
> My config files have the following lines:
>
> dev.ex:
>
> # Configure your database
>  config :adah, Adah.Repo,
>    adapter: Ecto.Adapters.Postgres,
>    username: "postgres",
>    password: "postgres",
>    database: "adah_dev",
>    hostname: "localhost",
>    pool_size: 10
>
> test.ex:
>
> # Configure your database
>  config :adah, Adah.Repo,
>  adapter: Ecto.Adapters.Postgres,
>  username: System.get_env("POSTGRES_USER") || "postgres",
>  password: System.get_env("POSTGRES_PASSWORD") || "postgres",
>  database: System.get_env("POSTGRES_DB") || "adah_test",
>  hostname: System.get_env("POSTGRES_HOST") || "localhost",
>  pool: Ecto.Adapters.SQL.Sandbox
>
> And I have no such errors while running tests or serving pages in dev
> environment, only when I run *mix ecto.migrate*.
>
> *When I use {:ecto, "== 2.0.0-beta.2", :phoenix_ecto, "== 3.0.0-beta.2"}
> everything works as excepted!*
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix_ecto/issues/45>
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by flomop** [comment]
@josevalim , thank's for reply! It just take me a lot of time to figure out that I should just add
`config :adah, ecto_repos: []` in my **config.exs** file:-)

**Comment by josevalim** [comment]
Fixed in Ecto master. :)

**Comment by kaermorchen** [comment]
@josevalim I catch this warning
```
$  mix ecto.migrate
warning: could not find repositories for application :instructor.

You can avoid this warning by passing the -r flag or by setting the
repositories managed by this application in your config/config.exs:

    config :instructor, ecto_repos: [...]

The configuration may be an empty list if it does not define any repo.
```
My deps are:
```
[{:phoenix, "~> 1.1.4"},
     {:mariaex, ">= 0.0.0"},
     {:ecto, "~> 2.0.0-rc.3", override: true},
     {:phoenix_ecto, "~> 3.0.0-rc.0"},
     {:gettext, "~> 0.9"},
     {:cowboy, "~> 1.0"},
     {:cors_plug, "~> 1.1"},
     {:guardian, "~> 0.10.0"},
     {:comeonin, "~> 2.4"},
     {:ja_serializer, "~> 0.8.1"}]
```

**Comment by josevalim** [comment]
Please update to the latest RC. In any case, you will have to set the `config :instructor, ecto_repos: [...]` in your "config/config.exs"/

**Comment by kaermorchen** [comment]
I use latest RC version. And when I add `config :instructor, ecto_repos: []` in `config/config.exs` migration not performed.

**Comment by flomop** [comment]
@kaermorchen Stanislav, try:

`mix ecto.migrate -r YourApp.Repo`

**Comment by josevalim** [comment]
@kaermorchen you need to include the repository in the configuration:

    config :instructor, ecto_repos: [Instructor.Repo]

**Comment by kaermorchen** [comment]
@josevalim that work, tanks.

**Comment by ashrafhasson** [comment]
I have a similar issue even after setting the Repo as `config :app, ecto_repos: [App.Repo]`, I still get the following errors:

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:admin, ["delete"]}
```

**Comment by josevalim** [comment]
Please include the full stacktrace and error message.

On Thursday, May 19, 2016, Ashraf Hasson <notifications@github.com> wrote:

> I have a similar issue even after setting the Repo as config :app,
> ecto_repos: [App.Repo], I still get the following errors:
>
> ** (Protocol.UndefinedError) protocol Enumerable not implemented for {:admin, ["delete"]}
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix_ecto/issues/45#issuecomment-220197745>
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ashrafhasson** [comment]
@josevalim really sorry, apparently the error I reported above was related to a bug in Guardian.

**Comment by jeroenhouben** [comment]
Ik also had to change this:

```
-config :peepchat, Peepchat.Endpoint,
+config :peepchat,
```

where peepchat is my app's name

**Comment by jeroenhouben** [comment]
Or, and I think this is the better way:

```
# Configures the endpoint
config :peepchat, Peepchat.Endpoint,
  url: [host: "localhost"],
  ...
config :peepchat, ecto_repos: [Peepchat.Repo]
```
