### ISSUE TITLE
Expecting form to be populated via changeset

### ISSUE THREAD

**Issue by curtislinden** [phoenixframework/phoenix_ecto#51]
I'm expecting my form to be populated via changeset (this is with ecto-2.0.0-rc6) and phoenix_ecto 3.0
     
I needed to explicitly do this 👍 
  
        changeset = Map.put(changeset,:params, params["user"])

Am I right in expecting this Form to have the changeset fields populated by default?

**Comment by josevalim** [comment]
@curtislinden you need to give us more information. If you build a change in your new action, you don't need to set the params explicitly.

**Comment by curtislinden** [comment]
In a create..

```
    result = User.changeset(%User{},user_params)
    |> Ecto.Changeset.put_assoc(:authorization,
                                build_authorization(authorization))
    |> Repo.insert
```
I construct a changset that will fail due to missing params
```
 {:error, reason} ->
        changeset = reason
        changeset = Map.put(changeset,:params, params["user"])
        conn
        |> put_flash(:error, "Could not Register. Errors in Form")
        |> render("register.html", changeset: changeset)
```
I render the form with the changeset.

**Comment by josevalim** [comment]
I have just tried this in an application and everything worked fine on this action:

```elixir
def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)

    case Repo.insert(changeset) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: user_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
end
```

so please let me know how to reproduce this, possibly in a sample application, because I cannot.

**Comment by curtislinden** [comment]
Thank you sir!

I isolated the issue and found everything to be functioning as expected. Then I took out 
```
use Guardian.Phoenix.Controller
```
and was able to establish the expected behaviour.

I will post an issue with Guardian.
