### ISSUE TITLE
ecto.create fails on windows

### ISSUE THREAD

**Issue by ramusbucket** [phoenixframework/phoenix_ecto#52]
I'm starting with Phoenix framework and trying to get my hands on - https://github.com/gitter-badger/phoenix-starter

When I try to `mix ecto.create` I get following error -

```
** (ArgumentError) argument error
    :erlang.byte_size(nil)
    lib/ecto/adapters/postgres.ex:83: Ecto.Adapters.Postgres.storage_up/1
    lib/mix/tasks/ecto.create.ex:34: anonymous fn/2 in Mix.Tasks.Ecto.Create.run/1
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

I'm clueless at this point about how to fix this. I have ` {:phoenix_ecto, "~> 2.0"}` dependency.

**Comment by josevalim** [comment]
Can you tell us what is the exact version for Ecto in your mix.lock file? You can also run "mix deps" and grab it from there.

**Comment by ramusbucket** [comment]
It seems `1.1.3`

**Comment by josevalim** [comment]
@ramusbucket you need to set those environment options: https://github.com/gitter-badger/phoenix-starter/blob/master/config/dev.exs#L27-L29 Otherwise there is no database and the command will fail.

**Comment by ramusbucket** [comment]
Yes, I have set them in .envrc for both (dev and test) variables.

**Comment by josevalim** [comment]
If you do echo $VAR_NAME, can you see the proper value? Because that seems
to be the only possible error here. Or try changing the config/dev.exs
system calls by actual values.

On Friday, June 17, 2016, ramusbucket <notifications@github.com> wrote:

> Yes, I have set them in .envrc for both (dev and test) variables.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/phoenixframework/phoenix_ecto/issues/52#issuecomment-226739181>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbioRitIpHW_EpFlYCxor7rbjbqIpks5qMnsygaJpZM4I4OYU>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ramusbucket** [comment]
Right, when I places actual values in place in dev.exs, it worked. But I was wondering why it did not read it from .envrc. Thanks a lot!

**Comment by ramusbucket** [comment]
I could get working by runing this command from `git bash` on windows 
` source .envrc && mix ecto.setup`
