### ISSUE TITLE
Enum fields in MySQL

### ISSUE THREAD

**Issue by clessg** [phoenixframework/phoenix_ecto#61]
This seems to work:

```elixir
add :gender, :enum, null: false, size: "'male', 'female'"
```

Is this the proper way to do it? It just seems weird to use the `size` option for this. Although I suppose the generated DDL is technically valid.

**Comment by josevalim** [comment]
You can always use `execute` to build it by hand. But ideally you may want to send a pull request to Ecto that adds proper adapter support in the migration DSL. :)
