### ISSUE TITLE
form_for changeset with errors

### ISSUE THREAD

**Issue by Grafikart** [phoenixframework/phoenix_ecto#66]
When a changeset is used to create a `%Phoenix.HTML.Form[}` errors seems to be ignored.

I found the explanation but I can't firgure why this line is used
https://github.com/phoenixframework/phoenix_ecto/blob/master/lib/phoenix_ecto/html.ex#L232

If I send a changeset containing errors to Phoenix.HTML.Form.form_for I would expect errors to be transmitted. 

```elixir
# Changeset with an error
comment = Comment.changeset(%Comment{username: "Hello"}, %{username: ""})
form_for comment, my_path, fn f -> 
    IO.inspect(f)
end

# IO.inspect(f)
%Phoenix.HTML.Form{
 data: %Blogmvc.Comment{ .... },
 errors: [], # <= not expected
 hidden: [],
 ....
 source: #Ecto.Changeset<
  action: nil,
  changes: %{username: nil},
  errors: [username: {"can't be blank", []}],
  data: #Blogmvc.Comment<>,
  valid?: false
  >
}
```

Maybe I'm missing something but action should not matter for this right ?

**Comment by josevalim** [comment]
You need to set the action in the changeset, otherwise, the changeset is considered like it was "committed" or "sent" to the repository. This is because folks may run validations even on the "new" action, for dry running or setting up some configs, and we don't want to show those then.

**Comment by chrismccord** [comment]
Please send support requests to the mailing list. If you believe you have experience a bug, please file the issue with the issue template filled out so we can properly help. In this case, the lack of an action on the changeset will not show errors; consider the case where you are building a resource for a new form, the changeset is "invalid", but you don't want to show errors. THe presence of an action taken on the changeset indicates we tried to take an action, and now the errors are meaningful.
