### ISSUE TITLE
Pass join parameters on assoc

### ISSUE THREAD

**Issue by cuongkta** [phoenixframework/phoenix_ecto#67]
I have the issue like this ecto's issue with phoenix_ecto: 
https://github.com/elixir-ecto/ecto/issues/1678

Pls advise. How to use 'on' query with paramater

from i in query,
      left_join: v in assoc(i, :votes)
      on: v.user_id = ^user_id 

How to make it works ?

**Comment by josevalim** [comment]
You need a comma after the second expression:

```elixir
from i in query,
left_join: v in assoc(i, :votes),
on: v.user_id = ^user_id
```

Also please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
