### ISSUE TITLE
Can't install phoenix_ecto with mix, error with git.

### ISSUE THREAD

**Issue by matrixise** [phoenixframework/phoenix_ecto#7]
When I try to install phoenix_ecto via mix I have an error, I don't have this problem if I clone the repository with git in a shell.
```elixir
{:phoenix, github: "phoenixframework/phoenix"},
{:phoenix_ecto, github: "phoenixframework/phoenix_ecto"},
```

```
* Getting phoenix_ecto (git://github.com/phoenixframework/phoenix_ecto.git)
Cloning into '/Users/stephane/dev/oci/deps/phoenix_ecto'...
remote: Counting objects: 123, done.
remote: Total 123 (delta 0), reused 0 (delta 0), pack-reused 123
Receiving objects: 100% (123/123), 15.43 KiB | 0 bytes/s, done.
Resolving deltas: 100% (46/46), done.
Checking connectivity... done.
fatal: reference is not a tree: ea5f6d90cfae8ab037d0cbe765660c98167ed4fd
** (Mix) Command `git --git-dir=.git checkout --quiet ea5f6d90cfae8ab037d0cbe765660c98167ed4fd` failed
```

Do you have an idea?

Thanks

**Comment by josevalim** [comment]
Can you run:

mix deps.unlock phoenix_ecto

And try again?

It seems your project is locked to a version that does not exist.


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by matrixise** [comment]
Works fine with unlock. After that, I removed the mix.lock file, the _build and deps/ directories and restart mix deps.get and no errors. Thank you.
