### ISSUE TITLE
`plug Phoenix.Ecto.SQL.Sandbox` doesn't share connection to sockets.

### ISSUE THREAD

**Issue by asiniy** [phoenixframework/phoenix_ecto#72]
I use `wallaby` for my feature tests, and my application uses websockets internally. While simple http request works pretty well, socket implementation brings me

``` elixir
Request: GET /socket/websocket?token=xxxx&vsn=1.0.0
** (exit) an exception was raised:
    ** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.577.0>.

When using ownership, you must manage connections in one
of the three ways:

  * By explicitly checking out a connection
  * By explicitly allowing a spawned process
  * By running the pool in shared mode

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

See Ecto.Adapters.SQL.Sandbox docs for more information.
```
I have an `Repo.get` query inside my `UserSocket` in order to authenticate

**Comment by josevalim** [comment]
Socket requests do not go through the plug pipeline, so there is nothing Phoenix.Ecto can do. One idea is for you to change your UserSocket to handle ownership mechanism, similar to what `Ecto.Adapters.SQL.Sandbox` does. Of course, you would do so only during the test environment.

**Comment by asiniy** [comment]
@josevalim sounds reasonable, but how could I do that?

**Comment by asiniy** [comment]
The whole behaviour doesn't look intuitive.

**Comment by josevalim** [comment]
Are you familiar with how the Ecto Sandbox works? If not, I would recommend getting started with the Ecto.Adapters.SQL.Sandbox docs.

The basic idea is that the test process owns the connection and therefore you need to tell the web request/web socket process who is the connection owner. Wallaby does that by encoding the test process information (literally the pid retrieved as `self()`) plus the repository name and then sends that as part of the user agent information. Then all Phoenix.Ecto.SQL.Sandbox does is to check if there is such information in the user agent and [call `sandbox.allow(repo, test_process_pid, self())`](https://github.com/phoenixframework/phoenix_ecto/blob/master/lib/phoenix_ecto/sql/sandbox.ex#L61).

You would need to do something similar: you would need to encode the test process information as a parameter (you could do that by calling :erlang.term_to_binary and then Base.url_encode64) and pass that parameter when you establish the socket connection. Now, inside your UserSocket, you would check if such parameter was sent and, if that's the case, unpack it and call sandbox.allow accordingly as well (which is exactly what Phoenix.Ecto.SQL.Sandbox does).

**Comment by asiniy** [comment]
@josevalim thanks for the detailed description. I knew it all.
The only question is how can I `pass that parameter when you establish the socket connection`?

Actually, yeah, I'll do something like

``` elixir
    :ok = Ecto.Adapters.SQL.Sandbox.checkout(MyApp.Repo)

    metadata = Phoenix.Ecto.SQL.Sandbox.metadata_for(MyApp.Repo, self())

    Application.put_env(:my_app, :safe_db_process, :erlang.term_to_binary(self()))
```

But how could I pass `:safe_db_process` to `socket`? I haven't found any option...

**Comment by asiniy** [comment]
The only relatively helpful thing I have found is `CowboyHandler` module https://github.com/phoenixframework/phoenix/blob/f2e02d97ef79f825f6bbbdc2d7b69a1d005bff90/lib/phoenix/endpoint/cowboy_handler.ex#L27 but the question about how could I pass this parameter still remains opened

**Comment by josevalim** [comment]
>     Application.put_env(:my_app, :safe_db_process, :erlang.term_to_binary(self()))

You cannot use Application.put_env because then you cannot run the tests concurrently as it is global storage. If you don't want to run the websocket tests concurrently, then you can set the sandbox to shared mode, as said in the error message.

> The only question is how can I pass that parameter when you establish the socket connection?

I have answered that above, you pass it as a request parameter, for example:

    GET /socket/websocket?token=xxxx&vsn=1.0.0&owner=#{encoded_base64_owner}

**Comment by asiniy** [comment]
@josevalim huge thanks!
Will write an article on weekend to back knowledge to the community. Will share it with you here, will be glad if you add it to elixir radar newsletter :)

**Comment by sergiotapia** [comment]
@asiniy How did you end up solving this? We're having trouble with our Wallaby tests as well because socket's fail in the exact same way you described here. Thanks for the info!

**Comment by viniciussbs** [comment]
@sergiotapia I ended up using shared mode for those kind of test - so they don't run asynchronously. But I guess you can try @josevalim idea. Just take a look at the recent change on Ecto Sandbox to offer better support for front-end apps testing - there's a blog post from DockYard about it.

**Comment by IcyEagle** [comment]
@asiniy if you're still interested in, I've found a hacky way how to make socket tests async.

You have to add a special line at the beginning of your _Channel.join_ function so I will look like this:
```elixir
  def join("my_channel", options, socket) do
    :ok = (Mix.env() == :test && Ecto.Adapters.SQL.Sandbox.allow(MyApp.Repo, socket.transport_pid, socket.channel_pid)) || :ok
   ...
  end
```

It allows you to start your Ecto session inside your tests and then reuse it within your channels. 

I inspected the code responsible for channel creation and concluded that at the moment there is no an elegant way to share the session with your channels (since _Channel.join_ function is called immediately after Channel's GenServer is created).

Hope it helps.

**Comment by rootkc** [comment]
> > ```
> > Application.put_env(:my_app, :safe_db_process, :erlang.term_to_binary(self()))
> > ```
> 
> You cannot use Application.put_env because then you cannot run the tests concurrently as it is global storage. If you don't want to run the websocket tests concurrently, then you can set the sandbox to shared mode, as said in the error message.
> 
> > The only question is how can I pass that parameter when you establish the socket connection?
> 
> You can pass it as a request parameter, for example:
> 
> ```
> GET /socket/websocket?token=xxxx&vsn=1.0.0&owner=#{encoded_base64_owner}
> ```

I am doing integration testing using wallaby and i solved my issue with `DBConnection.OwnershipError` for channels using the approach suggested by @josevalim.

When starting a session in my `feature_case.ex`

`    session
    |> Browser.visit("/")
    |> Browser.execute_script(
      "localStorage.setItem('socketOwner', arguments[0]);",
      [serialize_pid(self())]
    )`

In my `socket.js`

`const socketOwner = localStorage.getItem("socketOwner")
let socket = new Socket("/socket", {
  params: { token: window.userToken, socketOwner: socketOwner },
})`

And then i assign in to the socket in my `user_socket.ex` so i can this in my channel

`    if Application.get_env(:cash_cow, :sql_sandbox) do
      Ecto.Adapters.SQL.Sandbox.allow(
        CashCow.Repo,
        socket.assigns[:socket_owner],
        socket.channel_pid
      )
    end`

Hope this helps :)
