### ISSUE TITLE
Primary key requirement in `form_for_hidden`

### ISSUE THREAD

**Issue by Voronchuk** [phoenixframework/phoenix_ecto#73]
I was wondering why primary keys are required on this spot
```
defp form_for_hidden(%{__struct__: _} = data) do
      # Since they are primary keys, we should ignore nil values.
      for {k, v} <- Ecto.primary_key(data), v != nil, do: {k, v}
end
defp form_for_hidden(_), do: []
```

We use `embedded_schema` to store subdocuments inside single Mongo Object, with schema like the following:

```
    embedded_schema do
        field :name,                :string
        field :desc,                :string
        field :map_sprite,          :string

        embeds_one :attributes, Fatespinner.Character.Attributes

        belongs_to :account, Fatespinner.Account

        has_many :game_character, Fatespinner.GameCharacter

        timestamps
    end
```
where `Fatespinner.Character.Attributes` have to look like:

```
    @primary_key false
    embedded_schema do
        field :strength,        :integer,   default: @default_attribute_value,  primary_key: true
        field :dexterity,       :integer,   default: @default_attribute_value
        field :health,          :integer,   default: @default_attribute_value
        field :intelligence,    :integer,   default: @default_attribute_value
        field :wits,            :integer,   default: @default_attribute_value
        field :will,            :integer,   default: @default_attribute_value
        field :charisma,        :integer,   default: @default_attribute_value
        field :communication,   :integer,   default: @default_attribute_value
        field :empathy,         :integer,   default: @default_attribute_value
    end
```
This dummy primary key looks annoying, because it's set only not to trigger "missing primary key error" while editing nested embedded_schema with `inputs_for`.

**Comment by josevalim** [comment]
Please send a pull request. It made sense at the time when we originally added but it is no longer necessary.

**Comment by michalmuskala** [comment]
I guess it would be still required for associations of `:many` cardinality, but for singular associations it's indeed unnecessary.

**Comment by josevalim** [comment]
I think it is not necessary if you are using something like `on_replace: :delete`. You just refresh everything on every submit.

**Comment by LostKobrakai** [comment]
I've hit the same issue while trying to use schemaless changesets. It's about a form to add users to a newsletter. I'd only like to use the validation part of ecto and later delegate to the newsletter service's api.

**Comment by josevalim** [comment]
@LostKobrakai can you please try a PR and let us know how it goes? :)

**Comment by josevalim** [comment]
Or a failing test case to our test suite, which would help us a lot.

**Comment by LostKobrakai** [comment]
I've added a PR, but I'm not sure my fix for it is the best way to solve it.

**Comment by josevalim** [comment]
3.2.2 is out with @LostKobrakai's fix!
