### ISSUE TITLE
Empty :errors key in form object from changeset with nil action

### ISSUE THREAD

**Issue by samphilipd** [phoenixframework/phoenix_ecto#79]
I was scratching my head wondering why my `:errors` was empty in the form object even though there are errors in the changeset.

Then I found this commit https://github.com/phoenixframework/phoenix_ecto/commit/d374ed8017ff2252cf2da51d4d678e1d0c7ffc69 which sets errors to empty if the action is `nil`.

My question is, **why do this**? Are we supposed to usually set an action on the changeset? I can't find any docs on this or even how/why we should do that.

**Comment by chrismccord** [comment]
If no action has been applied to the changeset, no errors are shown. This is useful for things like validation hints on form fields. Imagine you build an empty changeset for a new form. That changeset isn't valid, but we don't want to show errors until an actual user action has been peformed. Likewise, we still may want to introspect the changeset for validation hints on fields to aid UX.  Thanks!

> Are we supposed to usually set an action on the changeset?

Ecto applies the action when you call Repo.insert/update/delete, but you can also set the action yourself. You can set it directly on the struct field, or use `apply_action/2` that was recently introduced on Ecto.Changeset. https://github.com/elixir-ecto/ecto/blob/544d36ac8c743a02c910ff4c52ca3c11252090a9/lib/ecto/changeset.ex#L1183-L1199

**Comment by samphilipd** [comment]
Thanks Chris that makes sense. I wonder if we could add something to the docs about this, since it might confuse people.

**Comment by josevalim** [comment]
@samphilipd can you please add some docs to phoenix_html form_for if appropriate? Thank you!
