### ISSUE TITLE
Add mix task for seeding the database

### ISSUE THREAD

**Issue by scrogson** [phoenixframework/phoenix_ecto#8]
I brought this idea to @ericmj and @chrismccord today, but it seems that we might need some more opinions on the matter.

The first idea was to add `mix ecto.seed` to Ecto. It would read `seed.exs` from `priv/repo/seeds`. This would allow users to seed their database following a nice convention.

Eric pointed out that this can be done really easily with `mix run priv/repo/seeds.exs`. But now I realize that the application probably needs to be started (or at least the `Repo` connected first). So it might be nice to provide a way to do this without boilerplate.

Eric also mentioned that maybe this should not be something concerned with Ecto but a separate application. I thought about `phoenix_ecto` for this.

Talking with Chris, he mentioned that we could just handle this by generating a mix task for the application `my_app/lib/mix/tasks/seed.ex` and have empty `seed/1` functions base on the environment that the user would have to fill out.

I still think that it would be nice to separate the task itself from the seed files. The task would start the repo and use `priv/repo/seeds/seed.exs` to insert records and whatnot. I think it's important to provide a clean interface for this.

```elixir
# priv/repo/seeds/seed.exs
use PhoenixEcto.Seed

import_seeds "users_#{Mix.env}.exs"
import_seeds "posts_#{Mix.env}.exs"
import_seeds "categories_#{Mix.env}.exs"
```

```elixir
# priv/repo/seeds/users_dev.exs
use PhoenixEcto.Seed

%User{name: "Sonny Scroggin", admin: true} |> Repo.insert
...
```

```
mix my_app.seed
```

Thoughts?

**Comment by chrismccord** [comment]
I am against the `import_seed` approach because it introduces more functions/macros where we could use a regular task. If we add an idiomatic seed setup, my vote is to generate a file like below. I also like that it acts as another avenue to introduce mix tasks to users early and make it part of their workflow. 

```elixir
defmodule Mix.Tasks.MyApp.Seed do
  use Mix.Task

  def run(_) do
    Mix.Task.run "app.start", []
    seed(Mix.env)
  end

  def seed(:dev) do
    # dev seeds
  end

  # def seed(:prod) do
  #   prod seeds, use with care
  # end
end
```

I am :+1: on coming up with a standard seeding approach

**Comment by ericmj** [comment]
> Eric pointed out that this can be done really easily with mix run priv/repo/seeds.exs. But now I realize that the application probably needs to be started (or at least the Repo connected first). So it might be nice to provide a way to do this without boilerplate.

Just FYI, `run` calls `app.start`. Starting the application will usually start the repo. Now that may not always because application startup may depend on data in the seed so we may need a custom task that can start the repo without starting the app (like `ecto.migrate` and friends).

**Comment by scrogson** [comment]
@chrismccord ok, so generate the task for the new application from the `phoenix.new` task and not from this `phoenix_ecto` application? If so, I'll start a PR shortly.

**Comment by josevalim** [comment]
I am with @ericmj here. I would go with mix run (which starts at the app
and repo) until we prove we need something more. Creating a seeds file with
information on how to run it with mix run is likely enough.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by HashNuke** [comment]
Apps might start other services on `app.start`. If the seeding feature is added, it would be nice to just start the repo worker and not the entire app to avoid problems (address-in-use and such).

Had an SMTP server, which was started with `app.start`. Now I check for the config option before starting the SMTP server.

```elixir
if Application.get_env(:phoenix, :serve_endpoints) do
  children = children ++ [worker(Firebrick.SmtpServer, [])]
end
```

[[ Thanks to @chrismccord for the tip about the `serve_endpoints` Phoenix config ]]

**Comment by josevalim** [comment]
By default `mix run` won't start the http endpoint, so we are covered.

**Comment by josevalim** [comment]
For those following at home, you can do: `mix run priv/repo/seeds.exs` in your Phoenix app and that's all. The `seeds.exs` file is full of comments to tell you what to do and what not to do.

**Comment by ryanwinchester** [comment]
@josevalim how about if we are using an umbrella application?

What if I want it seeded for all apps?

This works if I run the test from the app dir that has my `Repo`, but how can I make it also work from the umbrella root?

```elixir
  defp aliases do
    [
      "test": ["ecto.create --quiet", "ecto.migrate", "run priv/repo/test.seeds.exs", "test"]
    ]
  end
```

```
** (Mix) No such file: priv/repo/test.seeds.exs
```

![](http://drops.ryanwinchester.ca/1b0x1n203y2q/[54d885433a63f9f09fb0915c0b65d837]_Screen%2520Shot%25202018-01-16%2520at%252011.41.38%2520AM.png)

**Comment by fenollp** [comment]
Why is this in priv/? This folder is for static assets that an app in a release will need at runtime. A sub folder of lib/ sounds like a much better place and reduces runtime bloat.

**Comment by josevalim** [comment]
@fenollp since this is a script, it is not compiled in `lib`, and whatever is in `lib` does not make part of a release. To put it in other words, this file is not different than a ".sql" file or a ".sh" file. It is just written in Elixir. And to me the best place for scripts that I will need in production is priv or am I missing something?

**Comment by fenollp** [comment]
Right, I guess you can need to seed a DB in production.

**Comment by zimt28** [comment]
@chrismccord The Seed task suggested above has quite some advantages over the seed file coming with Phoenix, why not add it as a good default instead?

**Comment by josevalim** [comment]
Phoenix does support database seeds. It is a matter of “mix run
priv/repo/seed.exs”.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ryanwinchester** [comment]
This is often one of the first things I do when I set up a new phoenix project, is to add an `ecto.seed` alias:

```elixir
defp aliases do
    [
      "ecto.seed": ["run priv/repo/seeds.#{Mix.env()}.exs"],
      "ecto.setup": ["ecto.create", "ecto.migrate", "ecto.seed"],
      "ecto.reset": ["ecto.drop", "ecto.setup"],
      test: ["ecto.create --quiet", "ecto.migrate", "test"]
    ]
  end
```

Then have a `seeds.dev.exs`, `seeds.prod.exs`, ... etc files in `priv/repo`
