### ISSUE TITLE
MIX_ENV=prod mix ecto.migrations does not see all files

### ISSUE THREAD

**Issue by mvalitov** [phoenixframework/phoenix_ecto#81]
I ran into the problem that `mix ecto.migrate` and `mix ecto.migrations` does not see my last migration files in production mode. But sees them in mode dev
```
mars@ubuntu:~/temp_phoenix/my_balance$ mix ecto.migrations

Repo: MyBalance.Repo

  Status    Migration ID    Migration Name
--------------------------------------------------
  up        20170315204850  create_user
  up        20170319184713  create_session
  up        20170321195200  create_budget
  up        20170321200354  create_users_budgets
  up        20170322193636  add_name_to_budgets
  up        20170323200738  create_operation
  up        20170414202921  create_category
  up        20170414203307  add_category_id_to_operations
  up        20170416184614  add_confirm_token_to_users
  up        20170420204700  add_user_timestamp_to_operations
  up        20170421195002  create_invitation_code
  up        20170421214515  add_constraint_to_user_budget

mars@ubuntu:~/temp_phoenix/my_balance$ MIX_ENV=prod mix ecto.migrations

Repo: MyBalance.Repo

  Status    Migration ID    Migration Name
--------------------------------------------------
  up        20170315204850  create_user
  up        20170319184713  create_session
  up        20170321195200  create_budget
  up        20170321200354  create_users_budgets
  up        20170322193636  add_name_to_budgets
  up        20170323200738  create_operation
  up        20170414202921  create_category
  up        20170414203307  add_category_id_to_operations
```

I tried to execute `MIX_ENV=prod mix ecto.drop` and `MIX_ENV=prod mix ecto.create && MIX_ENV=prod mix ecto.migrate`, but this did not work.

What could be the reason?

versions: phoenix_ecto 3.2.3 , ecto 2.1.4

**Comment by josevalim** [comment]
Nothing comes to mind. Can you please provide a way to reproduce the issue?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by mvalitov** [comment]
I'm afraid I can not. The fact is that on another computer this problem is not there, all migrations work correctly. The problem only occurs on this server

**Comment by josevalim** [comment]
Without a mechanism to reproduce the error, I am afraid there isn't much we can do.

**Comment by mvalitov** [comment]
Can we communicate in some other way so that I can provide you with temporary access to my server?

**Comment by josevalim** [comment]
@mvalitov thanks for the offer but we have limited time to maintain projects and we cannot afford to use it for tracking issues on production servers. Sorry.

**Comment by mvalitov** [comment]
Yes, I understand you. I suggested this only because I copied all the code to another server, I did not find the problem. Hence, and giving you access to the source code, we will not fix anything. Thank you for the time devoted to my problem. Apparently, I have no other options but to work on another server, or completely clean up and reinstall on the current server?

**Comment by josevalim** [comment]
@mvalitov it seems to be the case. You can try yet a third server and see if the issue exists or not. If it does not, it is likely an issue with the first server unrelated to Ecto or Phoenix. FWIW, this is the first time I see such issue reported.

**Comment by mvalitov** [comment]
Removal and a new installation on the current server solved the problem
