### ISSUE TITLE
Set schema prefix on insert/insert!

### ISSUE THREAD

**Issue by tomciopp** [phoenixframework/phoenix_ecto#82]
When inserting a changeset/struct if you've set a prefix on insertion the resulting struct does not include the prefix in the Ecto.Schema.Metadata. My expectation is that this value should be set to whatever the value of the prefix was.

Here is the full problem that I'm having:

When testing I will often create some factories that need to be persisted to the database. However I run into issues due to the prefix not being available after insert when I want to find data that would be related to this object.

**Comment by josevalim** [comment]
Can you please provide code snippets of what you are doing, the results you are expecting and include your Phoenix and Ecto versions?

**Comment by tomciopp** [comment]
Ecto: 2.1.4
Phoenix:  1.2.3

Here is a factory module based off of what is in my app:
    defmodule MyApp.Factory do
      def build(:tenant) do 
         %MyApp.Tenant{name: "tenant"}
      end

      def build(:user) do
        %Scalpel.User{username: "example-#{System.unique_integer()}"}
      end
      
      def build(factory_name, attributes) do
        factory_name |> build() |> struct(attributes)
      end
      
      def insert!(:tenant) do 
        tenant = Repo.insert!(build(:tenant))
        # Runs all of the tenant specific migrations
        MyApp.TenantActions.create_tenant(Repo, tenant)
        tenant
      end

      def insert!(factory_name, attributes \\ [], prefix \\ "public") do
        Repo.insert! build(factory_name, attributes), prefix: prefix
      end
    end

# Test setup

   tenant = insert!(:tenant)
   user = insert(:user, [], build_prefix(tenant))

    let(:response) do 
      build_conn |> assign(:current_user, user)
    end

In a controller we have a plug function that loads the user's profile

    plug :load_profile, "before show" when action in [:show]

   # We get a failure here in our test because the profile table only 
   # exists under the schema of the tenant.
    def load_profile(%{current_user: user }) do 
       user |> Ecto.assoc(:profile) |> Repo.one()
    end

    def load_profile(conn, _opts) do 
       cond do 
          conn.assigns[:profile] ->
               conn
          profile = load_profile(conn.assigns) -> 
            conn |> assign(:profile, profile)
          true -> 
              conn |> redirect(to: page_path(conn, :index)) |> halt()
       end 
    end

My expectation is that if I have inserted the user with the tenant prefix when I run through my controller tests, I should be able to load it's profile if they are using the same schema. However I get an error since the inserted user believes that it has come from the public schema.

**Comment by josevalim** [comment]
Yes, you are correct. We should update the record if the prefix is given.
Can you please open up this issue in the Ecto repository?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
