### ISSUE TITLE
docs not published on hexdocs

### ISSUE THREAD

**Issue by auxbuss** [phoenixframework/phoenix_ecto#84]
https://hexdocs.pm/phoenix_ecto is returning a 404

Unexpected per https://hex.pm/docs/tasks#hex_publish

I discovered this when I found the docs weren't available to Dash.

**Comment by josevalim** [comment]
There are no docs for Phoenix.Ecto. It only implements protocols. Maybe publishing a documentation that says that though would be better than nothing.

**Comment by auxbuss** [comment]
In the English language, at least, there's a precedent for this: https://en.wikipedia.org/wiki/Intentionally_blank_page

I do think it would be useful.

**Comment by Eiji7** [comment]
@auxbuss and @josevalim: How about make `README.md` main page?
```elixir
docs: [
  main: "main",
  extras: ["README.md": [filename: "main", title: "Phoenix/Ecto"]]
]
```
Can I make PR for that?

**Comment by josevalim** [comment]
@Eiji7 sounds good, please do!
