### ISSUE TITLE
RFC: Make protocol implementations optional

### ISSUE THREAD

**Issue by alvinlindstam** [phoenixframework/phoenix_ecto#86]
We use phoenix_ecto, but does not always want to return or handle `Ecto.NoResultsError` as 404 pages. Would it be possible to make the implementations configurable (so that one might opt out of them while still using the rest of the project)?

# Reasoning

Let's assume we have the following route:

`item_path  GET   /item/:id       Project.Web.ItemController :show`

In the Controller, we'd use `Repo.get!(Item, id)` which of course should result in a 404 if not found since there is no matching resource.

But if we might also want to fetch other data through Ecto bang functions, where a NoResultsError is not an indication that the resource is unavailable but rather an application or data integrity error. In those cases we'd like to handle the error differently, and not return the 404 page.

In our case we would probably make the result explicit, such as using a `Repo.get_or_404!` helper, that would raise something like `Project.NotFoundError` with a custom implementation for `Plug.Exception`.

**Comment by josevalim** [comment]
Isn't returning 404 the most reasonable behaviour for the majority of your Ecto.NoResultsError though? This proposal only makes sense if most times this is the wrong result, so you want to swap the default.

**Comment by alvinlindstam** [comment]
Yes, I'm guessing that most `Ecto.NoResultsError`s in phoenix projects are actually 404s.

But with the protocol implementation, it's just not a default. If I understand things correctly, any `Ecto.NoResultsError` in a Controller will result in a 404, there is no way out.

You could try not to use the functions that raise those errors, but you might not be in control of all of them and it might not be suitable to raise other errors if developing some internal API that is not only intended to be used by phoenix controllers. If phoenix is only one of many interfaces to your application, you might not want to adapt the internal data handling functions to phoenix_ecto.

The other option would be to rescue any `Ecto.NoResultsError` when calling the internal API in the controllers, and raise some other error.

Neither of which seems very appealing.

**Comment by josevalim** [comment]
Sorry but I don't see how making it optional is going to make your options any better or worse. Imagine that you disable this, then what are you going to do next?

**Comment by alvinlindstam** [comment]
I would probably write something like

```elixir
defmodule NotFoundError do
  defexception [:message]
end


defmodule Project.Repo do
  use Ecto.Repo, otp_app: :project

  def get_or_404!(queryable, id, opts) do
    case get(queryable, id, opts) do
      nil ->
        raise NotFoundError, message: "Oops"
      other ->
        other
    end
  end
end

defimpl Plug.Exception, for: NotFoundError do
  def status(_), do: 404
end
```

Then I'd have to be explicit about when a missing object should be treated as a 404 instead of an application error by using `Repo.get_or_404!` when appropriate:

```elixir
defmodule Project.Web.ItemController do
  use Project.Web, :controller

  alias Project.{Repo, Item, User}
  def show(conn, params = %{"id" => id}) do
    item = Repo.get_or_404!(Item, id)
    random_user = Repo.get!(User, :rand.uniform(10))
    render(conn, :show, %{item: item, random_user: random_user})
  end
end
```

Disclaimer: I come from the Django community, and are used to doing this (by using their [`get_object_or_404`](https://docs.djangoproject.com/en/1.11/topics/http/shortcuts/#get-object-or-404) function. So this might very well be related to framework culture. But I also like the concept of being explicit about when an error is an unexpected exception and when it's just the normal flow of things.

We get some `Ecto.NoResultsError` reported to Sentry (our exception report tool), but most of them are just normal cases of resources not existing. But we can't really start ignoring all `Ecto.NoResultsError`s since they might also be a sign of application errors or data corruption.

**Comment by josevalim** [comment]
> I would probably write something like

You can write that today without touching the protocol implementation, no? The only reason to change the protocol implementation is if you want it to be a 500 instead of a 404.

**Comment by alvinlindstam** [comment]
Yes, but the response code (and the error page that we return to users) matters. Not *all* `Ecto.NoResultsError` are 404s, but the protocol implementation forces all of them to be handled as 404s.

**Comment by josevalim** [comment]
Just to be clear: 

> The only reason to change the protocol implementation is if you want it to be a 500 instead of a 404.

Is this what you want to do?

**Comment by alvinlindstam** [comment]
Yes

**Comment by josevalim** [comment]
Beautiful, PR please? :)

**Comment by alvinlindstam** [comment]
Yes, I'll take a look at an implementation.
