### ISSUE TITLE
Undefined function video_path/2

### ISSUE THREAD

**Issue by jorditudela** [phoenixframework/phoenix_ecto#88]
After running

 `mix​​ ​​phoenix.gen.html​​ ​​Video​​ ​​videos​​ ​​user_id:references:users​​ ​​​url:string​​ ​​title:string​​ ​​description:text​` 

and applying all indicated additional modifications I get a Compilation Error below:

```
== Compilation error on file web/controllers/video_controller.ex ==
** (CompileError) web/controllers/video_controller.ex:24: undefined function video_path/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1```

**Comment by josevalim** [comment]
Can you please make sure you added video_path to your router and saved the file? If it still fails, can you please provide an application that reproduces the error?

**Comment by jorditudela** [comment]
Sorry, my bad....

I made a typo when adding the `resources "/videos",  VideoController`
