### ISSUE TITLE
Changeset.apply_action/2 is not found.

### ISSUE THREAD

**Issue by sjoconnor** [phoenixframework/phoenix_ecto#90]
I'd like to use [`Ecto.Changeset.apply_action/2`](https://hexdocs.pm/ecto/Ecto.Changeset.html#apply_action/2) in my Phoenix app. I see it's available in version 2.2.1 of Ecto. Are there plans to bump the Ecto version used by `phoenix_ecto` to 2.2.1 anytime soon?

**Comment by josevalim** [comment]
@sjoconnor PhoenixEcto supports any Ecto version after 2.1. You can add `{:ecto, "~> 2.2.0"}` to your mix.exs and it should be picked up.

**Comment by sjoconnor** [comment]
I didn't realize that, thanks!
