### ISSUE TITLE
Set timeout for sandbox session

### ISSUE THREAD

**Issue by viniciussbs** [phoenixframework/phoenix_ecto#94]
Hi,

Is it possible to set the timeout for sandbox session? It seems like [the `SandboxSession` worker is ready to receive the timeout option](https://github.com/phoenixframework/phoenix_ecto/blob/be8e7c76085b16a04da4af5f39973d93029bfc73/lib/phoenix_ecto/sql/sandbox_session.ex#L12) but [the plug isn't passing the option](https://github.com/phoenixframework/phoenix_ecto/blob/be8e7c76085b16a04da4af5f39973d93029bfc73/lib/phoenix_ecto/sql/sandbox.ex#L100). Or am I missing something?

**Comment by josevalim** [comment]
I don't think we support it right now, so a PR would be appreciated!
