### ISSUE TITLE
Cannot Run seeds.exs

### ISSUE THREAD

**Issue by chinochao** [phoenixframework/phoenix_ecto#98]
Hi,

Every time I create a new html page using phx.gen.html and I try to create a seed I get this error message.

```
mix run priv/repo/seeds.exs
** (CompileError) priv/repo/seeds.exs:12: App.Statuses.__struct__/1 is undefined, cannot expand struct App.Statuses
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (elixir) expanding macro: Kernel.|>/2
    priv/repo/seeds.exs:12: (file)
```

**Comment by josevalim** [comment]
Can you make sure that `App.Statuses` is a module defined in your application?

If not, can you please include the relevant parts of your seeds file. It is likely that this isn't a phoenix_ecto bug and you are indeed trying to access a struct that does not exist in your application.
