### ISSUE TITLE
Relax version requirement of ecto?

### ISSUE THREAD

**Issue by rbao** [phoenixframework/phoenix_ecto#99]
Currently this package depends on with version `~> 2.1`, while ecto itself is already on `2.2.x` for quite some time now, so if this package is used then we can't take advantage of the newer feature from ecto 2.2.x

Wondering if the version requirement can be relaxed to include ecto 2.2.x, or is there anything blocking this change?

**Comment by rbao** [comment]
nvm it seems to work with ecto 2.2

**Comment by josevalim** [comment]
Yes! ~> 2.1 means 2.1, 2.2, 2.3, etc but not 3.0.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
